# Generated by Django 5.2.8 on 2026-01-25 08:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_customuser_address'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='bonus_points',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Бонусы'),
        ),
    ]
