# Generated by Django 5.2.8 on 2025-12-26 11:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0002_alter_product_options_product_is_holiday_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='HomeSection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=120, verbose_name='Заголовок секции')),
                ('slug', models.SlugField(unique=True)),
                ('is_active', models.BooleanField(default=True, verbose_name='Активна')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Порядок')),
                ('products', models.ManyToManyField(blank=True, to='store.product', verbose_name='Товары')),
            ],
            options={
                'verbose_name': 'Секция главной',
                'verbose_name_plural': 'Секции главной',
                'ordering': ['order'],
            },
        ),
    ]
