# Generated by Django 5.2.8 on 2025-11-29 16:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0002_subcategory'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='image',
        ),
    ]
