# Generated by Django 5.2.8 on 2026-04-13 12:13

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0006_alter_product_image'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='shopreview',
            options={'ordering': ['-created_at'], 'verbose_name': 'Отзыв о магазине', 'verbose_name_plural': 'Отзывы о магазине'},
        ),
        migrations.AddField(
            model_name='homesection',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='sections/', verbose_name='Баннер (картинка)'),
        ),
        migrations.AddField(
            model_name='homesection',
            name='link_section',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='linked_from', to='store.homesection', verbose_name='Ссылка на секцию'),
        ),
        migrations.AlterField(
            model_name='shopreview',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Дата создания'),
        ),
        migrations.AlterField(
            model_name='shopreview',
            name='is_approved',
            field=models.BooleanField(default=False, verbose_name='Одобрено админом'),
        ),
        migrations.AlterField(
            model_name='shopreview',
            name='text',
            field=models.TextField(verbose_name='Текст отзыва'),
        ),
        migrations.AlterField(
            model_name='shopreview',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Пользователь'),
        ),
    ]
