# Generated by Django 5.2.8 on 2026-05-05 06:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0008_chatmessage'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='chatmessage',
            name='reply',
        ),
        migrations.AddField(
            model_name='chatmessage',
            name='reply_json',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='chatmessage',
            name='reply_text',
            field=models.TextField(blank=True, null=True),
        ),
    ]
