# Generated by Django 5.2.8 on 2026-01-24 11:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_alter_order_options_order_delivery_address_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('processing', 'В обработке'), ('paid', 'Оплачен'), ('delivered', 'Доставлен')], default='processing', max_length=20),
        ),
    ]
